services:

  alpine-proxy:
    build:
        context: ./src
        dockerfile: Dockerfile
    image: alpine-proxy:latest
    container_name: alpine-proxy
    restart: unless-stopped
    ports:
      - "8654:8654"
    #environment:
      # Alpine Linux mirrors
      # Syntax: <proxy_path_1>::<remote_repo_1>,<proxy_path_2>::<remote_repo_2>
      # Example: ALPINE_REMOTES=alpine1::https://dl-cdn.alpinelinux.org,alpine2::mirror.yandex.ru
      #- ALPINE_REMOTES=
    volumes:
      - cache-data:/app/cache

volumes:
    cache-data: